// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz9yiRqO_0l0Wp1eQJeXLgcdvVA81ntxY',
    appId: '1:408906872347:web:47f3b879b3c59050db2abe',
    messagingSenderId: '408906872347',
    projectId: 'yandex-eat',
    authDomain: 'yandex-eat.firebaseapp.com',
    storageBucket: 'yandex-eat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzez-e9OiyMLBzrZnCk1bTEoASp4XjXTk',
    appId: '1:408906872347:android:11b0b75e43f7f08bdb2abe',
    messagingSenderId: '408906872347',
    projectId: 'yandex-eat',
    storageBucket: 'yandex-eat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBD2M69BkT4Qr7_wkRjdsTmi8yzhjMKJ4',
    appId: '1:408906872347:ios:40906202d68cf12adb2abe',
    messagingSenderId: '408906872347',
    projectId: 'yandex-eat',
    storageBucket: 'yandex-eat.appspot.com',
    iosBundleId: 'com.example.yandexEatsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBD2M69BkT4Qr7_wkRjdsTmi8yzhjMKJ4',
    appId: '1:408906872347:ios:40906202d68cf12adb2abe',
    messagingSenderId: '408906872347',
    projectId: 'yandex-eat',
    storageBucket: 'yandex-eat.appspot.com',
    iosBundleId: 'com.example.yandexEatsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz9yiRqO_0l0Wp1eQJeXLgcdvVA81ntxY',
    appId: '1:408906872347:web:e73165b521933765db2abe',
    messagingSenderId: '408906872347',
    projectId: 'yandex-eat',
    authDomain: 'yandex-eat.firebaseapp.com',
    storageBucket: 'yandex-eat.appspot.com',
  );

}